import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { map } from "@/apis/megaverse";
import { getMegaverse } from "@/utils/getMegaverse";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleClick = async () => {
    map()
      .then((res) => {
        getMegaverse(res.goal);
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <>
      <Head>
        <title>Megaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Megaverse</h1>
        <button
          style={{ width: 100, height: 50 }}
          onClick={() => handleClick()}
        >
          Create
        </button>
      </main>
    </>
  );
}
